version: "3.3"

networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=amnesia
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 1000:5432

  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - 2000:6379

  amnesia:
    image: amnesia:latest
    ports:
      - 3000:80
    environment:
      # CRITICAL: 50 | ERROR: 40 | WARNING: 30 | INFO: 20 | DEBUG: 10
      - LOG_LEVEL=20

      - READ_DB_USER=postgres
      - READ_DB_PASS=amnesia
      - READ_DB_HOST=postgres
      - READ_DB_PORT=5432
      - READ_DB_NAME=amnesia

      - WRITE_DB_USER=postgres
      - WRITE_DB_PASS=amnesia
      - WRITE_DB_HOST=postgres
      - WRITE_DB_PORT=5432
      - WRITE_DB_NAME=amnesia

      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/amnesia
    depends_on:
      - postgres
      - redis
