version: "3.3"

networks:
  default:
    driver: bridge

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=amnesia
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 1000:3306

  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - 2000:6379

  amnesia:
    image: amnesia:latest
    ports:
      - 3000:80
    environment:
      # CRITICAL: 50 | ERROR: 40 | WARNING: 30 | INFO: 20 | DEBUG: 10
      - LOG_LEVEL=20

      - READ_DB_USER=root
      - READ_DB_PASS=amnesia
      - READ_DB_HOST=mysql
      - READ_DB_PORT=3306
      - READ_DB_NAME=amnesia

      - WRITE_DB_USER=root
      - WRITE_DB_PASS=amnesia
      - WRITE_DB_HOST=mysql
      - WRITE_DB_PORT=3306
      - WRITE_DB_NAME=amnesia

      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/amnesia
    depends_on:
      - mysql
      - redis
