version: "3.3"

networks:
  default:
    driver: bridge

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=amnesia
      - MYSQL_ROOT_PASSWORD=amnesia
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis
    restart: always
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379

  amnesia:
    image: amnesia:latest
    restart: always
    ports:
      - 80:80
    environment:
      # CRITICAL: 50 | ERROR: 40 | WARNING: 30 | INFO: 20 | DEBUG: 10
      - LOG_LEVEL=20

      - DB_USER=root
      - DB_PASS=amnesia
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=amnesia

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - GEOLOCATION_DB_PATH=/ext/geoloc.mmdb
    depends_on:
      - mysql
      - redis
